// -------------------------------------------------------------
// 
// File Name: hdlsrc\sd_filter_tb\node_5.v
// Created: 2022-12-05 10:44:11
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: node_5
// Source Path: sd_filter_tb/SD 2nd Order Modulator/SD Filter/node_5
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module node_5
          (clk,
           reset,
           enb,
           input_rsvd,
           node_in,
           feedback,
           node_out);


  input   clk;
  input   reset;
  input   enb;
  input   input_rsvd;
  input   signed [1:0] node_in;  // sfix2_En1
  input   feedback;
  output  signed [24:0] node_out;  // sfix25


  wire signed [15:0] SD_Mux5_out1;  // int16
  wire signed [7:0] Gain_out1;  // sfix8_En1001
  wire signed [15:0] Sum1_stage2_add_cast;  // sfix16
  wire signed [15:0] Sum1_op_stage1;  // int16
  wire signed [24:0] Constant_out1;  // sfix25
  wire signed [15:0] SD_Mux1_out1;  // int16
  wire signed [15:0] Sum1_out1;  // int16
  wire signed [24:0] Sum2_stage2_add_temp;  // sfix25
  wire signed [24:0] Sum2_stage2_1;  // sfix25
  wire signed [25:0] Sum2_op_stage1;  // sfix26
  reg signed [24:0] Unit_Delay1_out1;  // sfix25
  wire signed [24:0] Sum2_stage3_add_cast;  // sfix25
  wire signed [24:0] Sum2_out1;  // sfix25


  SD_Mux5_block2 u_SD_Mux5 (.in1(input_rsvd),
                            .out1(SD_Mux5_out1)  // int16
                            );

  assign Gain_out1 = 8'sb00000000;



  assign Sum1_stage2_add_cast = {16{Gain_out1[7]}};
  assign Sum1_op_stage1 = SD_Mux5_out1 + Sum1_stage2_add_cast;



  assign Constant_out1 = 25'sb0000000000000000000000000;



  SD_Mux1_block2 u_SD_Mux1 (.in1(feedback),
                            .out1(SD_Mux1_out1)  // int16
                            );

  assign Sum1_out1 = Sum1_op_stage1 - SD_Mux1_out1;



  assign Sum2_stage2_1 = {{9{Sum1_out1[15]}}, Sum1_out1};
  assign Sum2_stage2_add_temp = Constant_out1 + Sum2_stage2_1;
  assign Sum2_op_stage1 = {Sum2_stage2_add_temp[24], Sum2_stage2_add_temp};



  assign Sum2_stage3_add_cast = Sum2_op_stage1[24:0];
  assign Sum2_out1 = Sum2_stage3_add_cast + Unit_Delay1_out1;



  always @(posedge clk or posedge reset)
    begin : Unit_Delay1_process
      if (reset == 1'b1) begin
        Unit_Delay1_out1 <= 25'sb0000000000000000000000000;
      end
      else begin
        if (enb) begin
          Unit_Delay1_out1 <= Sum2_out1;
        end
      end
    end



  assign node_out = Unit_Delay1_out1;

endmodule  // node_5

