vlib work
vlog  SD_Mux.v
vlog  SD_2nd_Order_Modulator_block.v
vlog  SD_Mux_block.v
vlog  SD_2nd_Order_Modulator1.v
vlog  SD_Mux8.v
vlog  SD_Mux1.v
vlog  SD_Mux5.v
vlog  node_2.v
vlog  SD_Mux1_block.v
vlog  SD_Mux5_block.v
vlog  node_3.v
vlog  SD_Mux1_block1.v
vlog  SD_Mux5_block1.v
vlog  node_4.v
vlog  SD_Mux1_block2.v
vlog  SD_Mux5_block2.v
vlog  node_5.v
vlog  SD_Filter.v
vlog  SD_2nd_Order_Modulator.v
