// -------------------------------------------------------------
// 
// File Name: hdlsrc\sd_filter_tb\SD_2nd_Order_Modulator.v
// Created: 2022-12-05 10:44:11
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 8.85771e-08
// Target subsystem base rate: 8.85771e-08
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        8.85771e-08
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// output_rsvd                   ce_out        8.85771e-08
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: SD_2nd_Order_Modulator
// Source Path: sd_filter_tb/SD 2nd Order Modulator
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module SD_2nd_Order_Modulator
          (clk,
           reset,
           clk_enable,
           input_rsvd,
           ce_out,
           output_rsvd);


  input   clk;
  input   reset;
  input   clk_enable;
  input   signed [15:0] input_rsvd;  // sfix16_En7
  output  ce_out;
  output  output_rsvd;


  wire SD_2nd_Order_Modulator1_out1;
  wire SD_2nd_Order_Modulator_out1;
  wire signed [46:0] SD_Filter_out1;  // sfix47_En22


  SD_2nd_Order_Modulator1 u_SD_2nd_Order_Modulator1 (.clk(clk),
                                                     .reset(reset),
                                                     .enb(clk_enable),
                                                     .in(input_rsvd),  // sfix16_En7
                                                     .out(SD_2nd_Order_Modulator1_out1)
                                                     );

  SD_Filter u_SD_Filter (.clk(clk),
                         .reset(reset),
                         .enb(clk_enable),
                         .input_rsvd(SD_2nd_Order_Modulator1_out1),
                         .feedback(SD_2nd_Order_Modulator_out1),
                         .output_rsvd(SD_Filter_out1)  // sfix47_En22
                         );

  SD_2nd_Order_Modulator_block u_SD_2nd_Order_Modulator (.clk(clk),
                                                         .reset(reset),
                                                         .enb(clk_enable),
                                                         .in(SD_Filter_out1),  // sfix47_En22
                                                         .out(SD_2nd_Order_Modulator_out1)
                                                         );

  assign output_rsvd = SD_2nd_Order_Modulator_out1;

  assign ce_out = clk_enable;

endmodule  // SD_2nd_Order_Modulator

