// -------------------------------------------------------------
// 
// File Name: hdlsrc\sd_filter_tb\SD_Mux5_block1.v
// Created: 2022-12-05 10:44:11
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: SD_Mux5_block1
// Source Path: sd_filter_tb/SD 2nd Order Modulator/SD Filter/node_4/SD_Mux5
// Hierarchy Level: 3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module SD_Mux5_block1
          (in1,
           out1);


  input   in1;
  output  signed [20:0] out1;  // sfix21_En8


  wire switch_compare_1;
  wire signed [20:0] Constant3_out1;  // sfix21_En8
  wire signed [20:0] Constant2_out1;  // sfix21_En8
  wire signed [20:0] Switch1_out1;  // sfix21_En8


  assign switch_compare_1 = in1 > 1'b0;



  assign Constant3_out1 = 21'sb111111101110101010001;



  assign Constant2_out1 = 21'sb000000010001010101111;



  assign Switch1_out1 = (switch_compare_1 == 1'b0 ? Constant3_out1 :
              Constant2_out1);



  assign out1 = Switch1_out1;

endmodule  // SD_Mux5_block1

