// -------------------------------------------------------------
// 
// File Name: hdlsrc\sd_filter_tb\SD_Mux_block.v
// Created: 2022-12-05 10:44:11
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: SD_Mux_block
// Source Path: sd_filter_tb/SD 2nd Order Modulator/SD 2nd Order Modulator1/SD_Mux
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module SD_Mux_block
          (in1,
           out1);


  input   in1;
  output  signed [15:0] out1;  // sfix16_En7


  wire switch_compare_1;
  wire signed [15:0] Constant3_out1;  // sfix16_En7
  wire signed [15:0] Constant2_out1;  // sfix16_En7
  wire signed [15:0] Switch1_out1;  // sfix16_En7


  assign switch_compare_1 = in1 > 1'b0;



  assign Constant3_out1 = 16'sb1111111110000000;



  assign Constant2_out1 = 16'sb0000000010000000;



  assign Switch1_out1 = (switch_compare_1 == 1'b0 ? Constant3_out1 :
              Constant2_out1);



  assign out1 = Switch1_out1;

endmodule  // SD_Mux_block

