// -------------------------------------------------------------
// 
// File Name: hdlsrc\sd_filter_tb\SD_Mux8.v
// Created: 2022-12-05 10:44:11
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: SD_Mux8
// Source Path: sd_filter_tb/SD 2nd Order Modulator/SD Filter/SD_Mux8
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module SD_Mux8
          (in1,
           out1);


  input   in1;
  output  signed [23:0] out1;  // sfix24_En22


  wire switch_compare_1;
  wire signed [23:0] Constant3_out1;  // sfix24_En22
  wire signed [23:0] Constant2_out1;  // sfix24_En22
  wire signed [23:0] Switch1_out1;  // sfix24_En22


  assign switch_compare_1 = in1 > 1'b0;



  assign Constant3_out1 = 24'sb111111111110111110011110;



  assign Constant2_out1 = 24'sb000000000001000001100010;



  assign Switch1_out1 = (switch_compare_1 == 1'b0 ? Constant3_out1 :
              Constant2_out1);



  assign out1 = Switch1_out1;

endmodule  // SD_Mux8

